### ISSUE TITLE
It's just not working.

### ISSUE THREAD

**Issue by zayd202** [Knawk/mc-MiniPracticeKit#2]
When I put the hotbar.nbt in the minecraft folder nothing is in a saved hotbar in game. I have tried going into the notepad and copying and pasting it into an existing hotbar.nbt but nothing still shows up.

**Comment by NOTNOTNOT123123** [comment]
how did you fixed it?

**Comment by zayd202** [comment]
make sure the nbt file is just "hotbar" and not hotbar (1) or something
like that. it has to just be the word hotbar.nbt
